# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Core Command

# Model Form Field configuration
form: $/tohur/bot/models/corecommands/fields.yaml

# Model Class name
modelClass: Tohur\Bot\Models\CoreCommands

# Default redirect location
defaultRedirect: tohur/bot/corecommands

# Create page
create:
    title: Create Core Command
    redirect: tohur/bot/corecommands/update/:id
    redirectClose: tohur/bot/corecommands

# Update page
update:
    title: Edit Core Command
    redirect: tohur/bot/corecommands
    redirectClose: tohur/bot/corecommands

# Preview page
preview:
    title: Preview Core Command
