# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: User

# Model Form Field configuration
form: $/tohur/bot/models/users/fields.yaml

# Model Class name
modelClass: Tohur\Bot\Models\Users

# Default redirect location
defaultRedirect: tohur/bot/users

# Create page
create:
    title: Create User
    redirect: tohur/bot/users/update/:id
    redirectClose: tohur/bot/users

# Update page
update:
    title: Edit User
    redirect: tohur/bot/users
    redirectClose: tohur/bot/users

# Preview page
preview:
    title: Preview User
