# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Permission

# Model Form Field configuration
form: $/tohur/bot/models/permission/fields.yaml

# Model Class name
modelClass: Tohur\Bot\Models\Permission

# Default redirect location
defaultRedirect: tohur/bot/permissions

# Create page
create:
    title: Create Permission
    redirect: tohur/bot/permissions/update/:id
    redirectClose: tohur/bot/permissions

# Update page
update:
    title: Edit Permission
    redirect: tohur/bot/permissions
    redirectClose: tohur/bot/permissions

# Preview page
preview:
    title: Preview Permission
